"""Updating tasks table

Revision ID: 1559bd9da4a5
Revises: 0a4fd41cdeeb
Create Date: 2024-09-18 22:00:43.357971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1559bd9da4a5'
down_revision = '0a4fd41cdeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
