"""Add unique constraint to message column in testimonials table

Revision ID: 21303faea386
Revises: 4c914b767391
Create Date: 2024-09-17 21:27:04.276733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21303faea386'
down_revision = '4c914b767391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.create_unique_constraint("message", ['message'])
        batch_op.create_unique_constraint("id", ['id'])
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
