"""Add subscribers table

Revision ID: ebde9ae0cf8b
Revises: f8e2dfadc380
Create Date: 2024-09-05 14:23:30.443179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebde9ae0cf8b'
down_revision = 'f8e2dfadc380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        # Name the unique constraint
        batch_op.create_unique_constraint('uq_subscribers_email', ['email'])
        batch_op.drop_column('emailaddress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emailaddress', sa.VARCHAR(length=255), nullable=True))
        # Drop the unique constraint by name
        batch_op.drop_constraint('uq_subscribers_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
